spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wad123456


mybatis:
  type-aliases-package: com.wonand.blog.pojo
  mapper-locations: classpath:/mapper/*.xml


#mysql分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    root: info
    com.wonand.blog: debug
  file:
    name: blog-dev.log
    path: /log


